apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: automation-hub
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: automation-hub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName: "" # set if your cluster has a specific StorageClass
